"use client";
import {useState} from "react";
import {createClient} from "@supabase/supabase-js";
const services={id:["Fiber Internet","Business Connectivity","Fiber Infrastructure","Network Solution"],en:["Fiber Internet","Business Connectivity","Fiber Infrastructure","Network Solution"]};
export default function SmartInquiry(){
 const [lang]=useState(()=>typeof window!=="undefined"?(localStorage.getItem("tscs-lang")||"id"):"id");
 const [service,setService]=useState(""); const [sent,setSent]=useState(false); const [busy,setBusy]=useState(false); const [err,setErr]=useState("");
 const t=lang==="en"?{name:"Name",company:"Company",email:"Email",phone:"Phone",service:"What do you need?",location:"Project / service location",message:"Tell us about your needs",send:"Start consultation",ok:"Thank you. Your consultation request has been received.",required:"Please complete the required fields."}:{name:"Nama",company:"Perusahaan",email:"Email",phone:"Telepon",service:"Apa yang Anda butuhkan?",location:"Lokasi proyek / layanan",message:"Ceritakan kebutuhan Anda",send:"Mulai Konsultasi",ok:"Terima kasih. Permintaan konsultasi Anda telah diterima.",required:"Lengkapi kolom yang wajib diisi."};
 async function submit(e){e.preventDefault();setErr("");setBusy(true);const f=new FormData(e.currentTarget);const name=f.get("name"),email=f.get("email"),message=f.get("message");if(!name||!email||!message){setErr(t.required);setBusy(false);return}try{const url=process.env.NEXT_PUBLIC_SUPABASE_URL,key=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;if(!url||!key)throw new Error("config");const sb=createClient(url,key);const {error}=await sb.from("inquiries").insert({name,company:f.get("company")||null,email,message:message+"\n\nService: "+(service||"General")+"\nPhone: "+(f.get("phone")||"")+"\nLocation: "+(f.get("location")||"")});if(error)throw error;setSent(true);e.currentTarget.reset()}catch(e){setErr(lang==="en"?"Unable to submit right now. Please try again later.":"Form belum dapat dikirim. Silakan coba lagi nanti.")}finally{setBusy(false)}}
 if(sent)return <div className="formSuccess"><span>✓</span><h3>{t.ok}</h3><button onClick={()=>setSent(false)}>{lang==="en"?"Send another":"Kirim lagi"}</button></div>;
 return <form className="smartForm" onSubmit={submit}><div className="formGrid"><label>{t.name} *<input name="name" required/></label><label>{t.company}<input name="company"/></label><label>{t.email} *<input name="email" type="email" required/></label><label>{t.phone}<input name="phone"/></label><label className="full">{t.service}<select value={service} onChange={e=>setService(e.target.value)}><option value="">—</option>{services[lang].map(x=><option key={x}>{x}</option>)}</select></label><label className="full">{t.location}<input name="location"/></label><label className="full">{t.message} *<textarea name="message" rows="6" required/></label></div>{err&&<p className="formError">{err}</p>}<button className="btn" disabled={busy}>{busy?"...":t.send}<span>↗</span></button></form>
}