import Link from "next/link";
import HeroMedia from "./components/hero-media";
import InteractiveNetwork from "./components/interactive-network";
import ScrollReveal from "./components/scroll-reveal";
const services=[["Fiber Internet","Koneksi fiber yang cepat dan stabil untuk menjaga operasional bisnis tetap terhubung."],["Business Connectivity","Konektivitas profesional untuk kantor, enterprise, dan kebutuhan jaringan bisnis."],["Fiber Infrastructure","Perencanaan dan pembangunan infrastruktur fiber optic yang terukur dan siap berkembang."],["Network Solution","Solusi jaringan yang dirancang mengikuti kebutuhan konektivitas dan infrastruktur bisnis."]];
const strengths=[["Fiber Optic Connectivity","Fondasi konektivitas berbasis fiber optic untuk kebutuhan yang menuntut stabilitas."],["Network Infrastructure","Infrastruktur jaringan yang dirancang dengan pendekatan terukur dan berorientasi jangka panjang."],["Business Connectivity","Solusi konektivitas yang menempatkan kebutuhan operasional bisnis sebagai prioritas."],["Scalable Solution","Arsitektur jaringan yang dapat dikembangkan mengikuti pertumbuhan kebutuhan."]];
export default function Home(){return <><section className="heroHome"><div className="heroCopy"><span className="eyebrow">TELECOMMUNICATION • FIBER OPTIC • CONNECTIVITY</span><h1>Koneksi yang <em>Menggerakkan.</em><br/>Infrastruktur yang <em>Menguatkan.</em></h1><p>Menghadirkan konektivitas fiber optic dan solusi jaringan modern untuk membangun infrastruktur digital yang cepat, stabil, dan siap berkembang.</p><div className="actions"><Link href="/kontak" className="btn">Mulai Konsultasi <span>↗</span></Link><Link href="/layanan" className="btn ghost">Jelajahi Layanan</Link></div></div><HeroMedia/></section>
<ScrollReveal><section className="trustSection"><div className="sectionHead"><span className="eyebrow">PT. TIGA SERANGKAI CAHAYA SELATAN</span><h2>Membangun fondasi konektivitas untuk bisnis yang terus bergerak.</h2></div><div className="trustGrid">{strengths.map(([t,d])=><article className="trustItem" key={t}><span className="trustDot"/><h3>{t}</h3><p>{d}</p></article>)}</div></section></ScrollReveal>
<ScrollReveal><section className="section servicesSection"><div className="sectionHead rowHead"><div><span className="eyebrow">OUR SERVICES</span><h2>Layanan yang Menghubungkan Bisnis Anda.</h2></div><Link href="/layanan" className="textLink">Lihat semua layanan <span>→</span></Link></div><div className="serviceCards homeServiceCards">{services.map(([t,d],i)=><Link href={"/layanan/"+["fiber-internet","business-connectivity","fiber-infrastructure","network-solution"][i]} className="serviceCard" key={t}><span>0{i+1}</span><div className="cardNetwork"/><h3>{t}</h3><p>{d}</p><b>Explore ↗</b></Link>)}</div></section></ScrollReveal>
<ScrollReveal><section className="networkSection"><div className="networkMapLarge"><div className="mapShape"/><span className="mapNode n1"/><span className="mapNode n2"/><span className="mapNode n3"/><span className="mapNode n4"/><InteractiveNetwork/></div><div className="networkCopy"><span className="eyebrow">NETWORK / COVERAGE</span><h2>Jaringan yang Menjangkau Lebih Jauh.</h2><p>Visualisasi jaringan Indonesia sebagai gambaran konektivitas. Ketersediaan aktual bergantung pada lokasi dan infrastruktur yang tersedia.</p><Link href="/jaringan" className="btn">Cek Ketersediaan <span>↗</span></Link></div></section></ScrollReveal>
<ScrollReveal><section className="section technologySection"><div className="sectionHead"><span className="eyebrow">INFRASTRUCTURE & TECHNOLOGY</span><h2>Infrastruktur yang Menggerakkan Koneksi.</h2></div><div className="techGrid"><div className="techVisual"><div className="techCore">FIBER</div><div className="techRing tr1"/><div className="techRing tr2"/><div className="techRing tr3"/><span className="techPulse tp1"/><span className="techPulse tp2"/><span className="techPulse tp3"/></div><div className="techPoints"><div><span>01</span><div><h3>Fiber Optic</h3><p>Fondasi transmisi berkapasitas tinggi.</p></div></div><div><span>02</span><div><h3>Network Infrastructure</h3><p>Jaringan yang dirancang untuk operasional yang konsisten.</p></div></div><div><span>03</span><div><h3>Scalable Architecture</h3><p>Solusi yang dapat berkembang mengikuti kebutuhan.</p></div></div></div></div></section></ScrollReveal>
<ScrollReveal><section className="aboutSection"><div className="aboutPanel"><span className="eyebrow">ABOUT TSCS</span><h2>Tentang TSCS.</h2><p>PT. TIGA SERANGKAI CAHAYA SELATAN hadir dengan fokus pada konektivitas, fiber optic, dan infrastruktur jaringan untuk membantu menciptakan fondasi digital yang lebih andal bagi bisnis.</p><p>TSCS memandang jaringan bukan sekadar koneksi, tetapi sebagai infrastruktur yang memungkinkan bisnis bergerak lebih cepat dan berkembang dengan percaya diri.</p><Link href="/tentang-kami" className="textLink">Mengenal TSCS <span>→</span></Link></div></section></ScrollReveal>
<section className="finalCta"><div className="finalNetwork"><InteractiveNetwork/></div><span className="eyebrow">LET'S CONNECT</span><h2>Siap Terhubung dengan<br/><em>Infrastruktur yang Lebih Baik?</em></h2><Link href="/kontak" className="btn">Bangun Koneksi Bersama TSCS <span>↗</span></Link></section></>